name: ${project.name}
main: me.Fupery.ArtMap.ArtMap
version: ${project.version}
description: ${project.description}
depends: []
author: Fupery

commands:
  artmap:
      usage:  |
        <command> save <title> : Saves your artwork
        <command> delete <title> : Removes your artwork
        <command> preview <title> : Previews an artwork
        <command> list <playername|all> <pg> : Lists artworks
        <command> help : Displays help
        <command> recipe <item> : displays recipe for players, give item to admin
        <command> backup : Creates a backup of all current artworks
        <command> restore : <backupname> <worldname> <-o>
permissions:
  artmap.artist:
    description: Allows creation of artworks
    default: op
  artmap.admin:
    description: Allows administrative commands
    children:
      artmap.artist: true
    default: op